Repository live-image-tracking-tools/traccuracy, pull requests merged in 2023-11, with the labels that each got.

#71 docs: fix docs build, fix all build warnings, enable strict mode
  .readthedocs.yml
  README.md
  docs/source/cli.rst
  docs/source/conf.py
  docs/source/index.rst
  pyproject.toml
  src/traccuracy/_tracking_graph.py
  src/traccuracy/cli.py
  src/traccuracy/loaders/_ctc.py
  src/traccuracy/matchers/_iou.py
  src/traccuracy/metrics/_divisions.py
Labels: documentation

#112 Adding track overlap metrics from `laptrack`
  src/traccuracy/_tracking_graph.py
  src/traccuracy/metrics/_track_overlap.py
  tests/metrics/test_divisions.py
  tests/metrics/test_track_overlap_metrics.py
  tests/test_utils.py
Labels: enhancement, topic: metrics

#109 Refactor `Metrics` class to pass data into compute method not constructor
  src/traccuracy/_run_metrics.py
  src/traccuracy/metrics/_base.py
  src/traccuracy/metrics/_ctc.py
  src/traccuracy/metrics/_divisions.py
  src/traccuracy/metrics/_track_overlap.py
  tests/bench.py
  tests/metrics/test_ctc_metrics.py
  tests/metrics/test_divisions.py
  tests/metrics/test_track_overlap_metrics.py
Labels: topic: metrics

#124 Fix subclass docstrings for sphinx autoapi
  src/traccuracy/matchers/_iou.py
  src/traccuracy/metrics/__init__.py
  src/traccuracy/metrics/_divisions.py
Labels: documentation

#118 Update `run_metrics` to take instantiated `Matchers` and `Metrics` as input
  examples/ctc.ipynb
  src/traccuracy/_run_metrics.py
  src/traccuracy/_utils.py
  src/traccuracy/cli.py
  src/traccuracy/track_errors/_ctc.py
  tests/test_run_metrics.py
Labels: enhancement
