Repository live-image-tracking-tools/traccuracy, pull requests merged in 2025-07, with the labels that each got.

#268 Add a larger test case with multiple tracks and frames
  docs/source/test_cases/index.md
  docs/source/test_cases/larger_examples.md
  tests/examples/larger_examples.py
Labels: :test_tube: tests

#267 Update some docstrings
  src/traccuracy/loaders/_ctc.py
  src/traccuracy/matchers/__init__.py
  src/traccuracy/matchers/_base.py
  src/traccuracy/metrics/_ctc.py
  src/traccuracy/metrics/_divisions.py
Labels: :memo: documentation

#247 Implement cell cycle accuracy metric
  docs/source/metrics/ctc.md
  pyproject.toml
  src/traccuracy/metrics/__init__.py
  src/traccuracy/metrics/_ctc.py
  tests/bench.py
  tests/metrics/test_ctc_metrics.py
Labels: :star: enhancement, topic: metrics

#265 Documentation updates
  .gitignore
  README.md
  docs/source/conf.py
  docs/source/glossary.md
  docs/source/index.md
  docs/source/metrics/basic.md
  docs/source/metrics/ctc.md
  docs/source/metrics/divisions.md
  docs/source/test_cases/errors.md
  docs/source/track_errors/basic.md
  docs/source/track_errors/ctc.md
  docs/source/track_errors/divisions.md
  docs/source/track_errors/gap_closing.rst
  pyproject.toml
  scripts/download_test_data.py
  src/traccuracy/_run_metrics.py
  src/traccuracy/_tracking_graph.py
  src/traccuracy/cli.py
  src/traccuracy/loaders/_ctc.py
  src/traccuracy/matchers/__init__.py
  src/traccuracy/matchers/_base.py
  src/traccuracy/matchers/_compute_overlap.py
  src/traccuracy/matchers/_matched.py
  src/traccuracy/metrics/__init__.py
  src/traccuracy/metrics/_base.py
  src/traccuracy/metrics/_basic.py
  src/traccuracy/metrics/_ctc.py
  src/traccuracy/metrics/_divisions.py
  src/traccuracy/metrics/_results.py
  src/traccuracy/metrics/_track_overlap.py
  src/traccuracy/track_errors/_basic.py
  src/traccuracy/track_errors/_ctc.py
  src/traccuracy/track_errors/_divisions.py
  src/traccuracy/utils.py
  tests/examples/graphs.py
  tests/matchers/test_base.py
  tests/matchers/test_matched.py
  tests/metrics/test_base.py
  tests/metrics/test_divisions.py
  tests/metrics/test_track_overlap_metrics.py
  tests/track_errors/test_ctc_errors.py
  tests/track_errors/test_divisions.py
Labels: :memo: documentation

#283 Ensure point loader always returns positive integer IDs
  src/traccuracy/loaders/_point.py
  tests/loaders/test_point.py
Labels: topic: loader, fix

#282 Update test cases to remove string ids
  tests/examples/graphs.py
  tests/examples/segs.py
  tests/matchers/test_ctc.py
  tests/matchers/test_iou.py
  tests/matchers/test_point_seg.py
  tests/test_tracking_graph.py
  tests/test_utils.py
Labels: :test_tube: tests

#281 Refactor ctc loader to use uint ids
  src/traccuracy/loaders/_ctc.py
  tests/loaders/test_ctc.py
Labels: topic: loader, fix

#288 Implement a loader for geff data
  .gitignore
  pyproject.toml
  src/traccuracy/loaders/__init__.py
  src/traccuracy/loaders/_geff.py
  tests/loaders/test_geff.py
Labels: :star: enhancement

#292 Remove some ctc functions from public export
  src/traccuracy/loaders/__init__.py
  src/traccuracy/loaders/_ctc.py
  tests/bench.py
  tests/loaders/test_ctc.py
  tests/matchers/test_iou.py
Labels: :hammer: maintenance

#294 Raise error if only one graph has error annotations
  src/traccuracy/track_errors/_basic.py
  src/traccuracy/track_errors/_ctc.py
  src/traccuracy/track_errors/_divisions.py
  tests/metrics/test_basic.py
  tests/test_utils.py
  tests/track_errors/test_basic.py
  tests/track_errors/test_ctc_errors.py
  tests/track_errors/test_divisions.py
Labels: :bug: bug

#293 Check that node ids are positive integers
  src/traccuracy/_tracking_graph.py
  src/traccuracy/loaders/_point.py
  tests/loaders/test_point.py
  tests/matchers/test_iou.py
  tests/test_tracking_graph.py
  tests/test_utils.py
  tests/track_errors/test_ctc_errors.py
Labels: :hammer: maintenance
