Repository live-image-tracking-tools/traccuracy, pull requests merged in 2025-03, with the labels that each got.

#209 Point matcher
  .github/PULL_REQUEST_TEMPLATE/new_matcher_metric.md
  docs/source/index.rst
  docs/source/matchers/matchers.md
  docs/source/test_cases/divisions.pct.py
  docs/source/test_cases/errors.pct.py
  docs/source/test_cases/index.rst
  docs/source/test_cases/matchers.pct.py
  src/traccuracy/matchers/__init__.py
  src/traccuracy/matchers/_base.py
  src/traccuracy/matchers/_iou.py
  src/traccuracy/matchers/_point.py
  tests/bench.py
  tests/examples/segs.py
  tests/matchers/test_point.py
  tests/test_utils.py
Labels: enhancement, topic: matcher

#221 Replace black with ruff-format in precommit
  .pre-commit-config.yaml
  docs/source/test_cases/divisions.pct.py
  docs/source/test_cases/errors.pct.py
  docs/source/track_errors/basic.pct.py
  examples/ctc.ipynb
  pyproject.toml
  scripts/test_case_report.py
  src/traccuracy/_run_metrics.py
  src/traccuracy/_tracking_graph.py
  src/traccuracy/cli.py
  src/traccuracy/loaders/__init__.py
  src/traccuracy/loaders/_ctc.py
  src/traccuracy/matchers/__init__.py
  src/traccuracy/matchers/_base.py
  src/traccuracy/matchers/_compute_overlap.py
  src/traccuracy/matchers/_iou.py
  src/traccuracy/matchers/_point.py
  src/traccuracy/metrics/_base.py
  src/traccuracy/metrics/_ctc.py
  src/traccuracy/metrics/_divisions.py
  src/traccuracy/metrics/_track_overlap.py
  src/traccuracy/track_errors/__init__.py
  src/traccuracy/track_errors/_ctc.py
  src/traccuracy/track_errors/basic.py
  src/traccuracy/track_errors/divisions.py
  tests/bench.py
  tests/examples/graphs.py
  tests/examples/segs.py
  tests/loaders/test_ctc.py
  tests/matchers/test_base.py
  tests/matchers/test_compute_overlap.py
  tests/matchers/test_ctc.py
  tests/matchers/test_iou.py
  tests/matchers/test_point.py
  tests/metrics/test_base.py
  tests/metrics/test_ctc_metrics.py
  tests/metrics/test_divisions.py
  tests/metrics/test_track_overlap_metrics.py
  tests/metrics/test_weighted_error_sums.py
  tests/test_tracking_graph.py
  tests/test_utils.py
  tests/track_errors/test_basic.py
Labels: CI

#220 Configure pixi for traccuracy
  .gitattributes
  .gitignore
  developer_notes.md
  pixi.lock
  pyproject.toml
Labels: dependencies

#227 Drop python 39
  .github/workflows/ci.yml
  pixi.lock
  pyproject.toml
  scripts/test_case_report.py
  src/traccuracy/matchers/_compute_overlap.py
  src/traccuracy/matchers/_iou.py
  src/traccuracy/matchers/_point.py
  tests/examples/graphs.py
  tests/examples/segs.py
  tests/matchers/test_compute_overlap.py
  tests/matchers/test_iou.py
  tests/metrics/test_divisions.py
  tests/track_errors/test_divisions.py
Labels: dependencies

#218 Improve runtime of `TrackOverlap` metrics
  src/traccuracy/_tracking_graph.py
  src/traccuracy/metrics/_track_overlap.py
  tests/bench.py
  tests/test_tracking_graph.py
Labels: performance, topic: metrics

#222 Update docs to use exclusively Myst Md
  docs/source/_static/css/tablefix.css
  docs/source/cli.md
  docs/source/conf.py
  docs/source/index.md
  docs/source/index.rst
  docs/source/metrics/basic.md
  docs/source/metrics/basic.rst
  docs/source/metrics/ctc.md
  docs/source/metrics/divisions.md
  docs/source/metrics/divisions.rst
  docs/source/metrics/track_overlap.md
  docs/source/metrics/track_overlap.rst
  docs/source/test_cases/divisions.md
  docs/source/test_cases/errors.md
  docs/source/test_cases/index.md
  docs/source/test_cases/matchers.md
  docs/source/track_errors/basic.md
  docs/source/track_errors/ctc.md
  docs/source/track_errors/ctc.rst
  docs/source/track_errors/divisions.md
  docs/source/track_errors/divisions.rst
  pyproject.toml
Labels: documentation

#127 Add tests for correct usage of gap-closing or frame-skip edges
  README.md
  docs/source/index.md
  docs/source/test_cases/divisions.md
  docs/source/test_cases/errors.md
  docs/source/track_errors/basic.md
  docs/source/track_errors/ctc.md
  docs/source/track_errors/divisions.md
  docs/source/track_errors/gap_closing.rst
  scripts/test_case_report.py
  src/traccuracy/_tracking_graph.py
  tests/examples/graphs.py
  tests/loaders/test_ctc.py
  tests/metrics/test_track_overlap_metrics.py
  tests/track_errors/test_basic.py
  tests/track_errors/test_ctc_errors.py
  tests/track_errors/test_divisions.py
Labels: tests

#232 Update dev docs with instructions to use pixi for building docs
  developer_notes.md
Labels: documentation

#230 Add python 312 and 313
  .github/workflows/benchmark-report.yml
  .github/workflows/ci.yml
  pyproject.toml
Labels: dependencies

#236 CTC loader checks dimensionality of data to set TrackingGraph loc keys
  src/traccuracy/loaders/_ctc.py
  tests/loaders/test_ctc.py
Labels: fix

#234 Implement a point to segmentation matcher
  docs/source/matchers/matchers.md
  src/traccuracy/loaders/_ctc.py
  src/traccuracy/matchers/__init__.py
  src/traccuracy/matchers/_point_seg.py
  tests/bench.py
  tests/matchers/test_point_seg.py
Labels: enhancement, topic: matcher
